name: PredBit
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - joblib
  - xgboost
  - pytest
  - pip
  - pip:
    - fastapi
    - uvicorn