apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: predbit-al-hpa
  namespace: predbit-al-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: predbit-al-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50