paths:
  raw: data/raw/mental_health_digital_behavior_data.csv
  processed_dir: data/processed
  model_dir: models

target:
  name: keep_habit
  rule:
    column: digital_wellbeing_score
    threshold: 60

split:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  stratify: true

features:
  numeric:
    - daily_screen_time_min
    - sleep_hours
    - notification_count
    - social_media_time_min
    - focus_score
    - mood_score
    - anxiety_level
  categorical: []